name: Build and push with Podman


on:
  push:
    branches: [ "main" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          sudo mkdir -p /etc/containers
          echo -e '[registries.search]\nregistries = ["docker.io"]' | sudo tee /etc/containers/registries.conf


      - name: Docker Hub Login
        env:
          DOCKERHUB_USER: ${{ secrets.pupsik812 }}
          DOCKERHUB_TOKEN: ${{ secrets.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 }}
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | podman login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io


      - name: Build and Push
        run: |
          IMAGE_NAME="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/my-podman-app:latest"


          podman build -t $IMAGE_NAME .
          podman push $IMAGE_NAME
