name: Build and push with Podman


on:
  push:
    branches: [ "main" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman podman-docker
          sudo mkdir -p /etc/containers
          echo -e '[registries.search]\nregistries = ["docker.io"]' | sudo tee /etc/containers/registries.conf

          echo "podman:100000:65536" | sudo tee /etc/subuid
          echo "podman:100000:65536" | sudo tee /etc/subgid
          mkdir -p ~/.local/share/containers
          chmod 755 ~/.local/share/containers


      - name: Configure Docker Hub auth
        run: |
          mkdir -p ~/.docker
          echo'{"auths":{"docker.io":{"auth":"'$(echo -n"${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" | base64 -w0)'"}}' > ~/.docker/config.json
          chmod 600 ~/.docker/config.json)


      - name: Build and push image
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME}}
        run: |
          podman build -t docker.io/${{ secrets.DOCKERHUB_USERNAME/my-podman-app:latest .
          podman push docker.io/${{ secrets.DOCKERHUB_USERNAME/my-podman-app:latest
