name: Build and push with Podman


on:
  push:
    branches: [ "main" ]


env:
  DOCKERHUB_USERNAME: ${{ secrets.:pupsik812/my-podman-app.git }}
  DOCKERHUB_TOKEN: ${{ secrets.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 }}
  IMAGE_NAME: "my-podman-app"


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman


      - name: Log in to Docker Hub
        run: |
          echo "$DOCKERHUB_TOKEN" | podman login -u "$DOCKERHUB_USERNAME" --password-stdin docker.io


      - name: Build and Push
        run: |
          podman build -t "$DOCKERHUB_USERNAME/$IMAGE_NAME:latest" .
          podman push "$DOCKERHUB_USERNAME/$IMAGE_NAME:latest"
