name: Build and push with Podman


on:
  push:
    branches: [ "main" ]


env:
   DOCKERHUB_USER: ${{ secrets.pupsik812 }}
    DOCKERHUB_TOKEN: ${{ secrets.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 }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman podman-docker
          sudo mkdir -p /etc/containers
          echo -e '[registries.search]\nregistries = ["docker.io"]' | sudo tee /etc/containers/registries.conf


      - name: Login to Docker Hub
        run: |
          echo "$DOCKERHUB_TOKEN" | podman login -u "$DOCKERHUB_USERNAME" --password-stdin docker.io


      - name: Build and Push
        run: |
          podman build -t "docker.io/$DOCKERHUB_USERNAME/my-podman-app:latest" .
          podman push "docker.io/$DOCKERHUB_USERNAME/my-podman-app:latest"
