name: Build and push with Podman


on:
  push:
    branches: [ "main" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman


      - name: Log in to Docker Hub
        run: |
          podman login -u ${{ secrets.:pupsik812/my-podman-app.git }} -p ${{ secrets.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 }} docker.oi


      - name: Build and Push
        run: |
          podman build -t ${{ secrets.:pupsik812/my-podman-app.git }}/my-podman-app:latest .
          podman push ${{ secrets.:pupsik812/my-podman-app.git}}/my-podman-app:latest
