name: Build and push with Podman


on:
  push:
    branches: [ "maim" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman podman-docker
          sudo mkdir -p /etc/containers
          echo -e '[registries.search]\nregistries = ["docker.io"]' | sudo tee /etc/containers/registries.conf


      - name: Login to Docker Hub
        env:
          DOCKERHUB_USER: ${{ secrets.pupsik812 }}
          DOCKERHUB_TOKEN: ${{ secrets.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 }}
        run: |
          echo "$DOCKERHUB_TOKEN" | podman login -u "$DOCKERHUB_USERNAME" --password-stdin docker.io


      - name: Build and Push
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME}}
        run: |
          podman build -t "docker.io/$DOCKERHUB_USERNAME/my-podman-app:latest" .
          podman push "docker.io/$DOCKERHUB_USERNAME/my-podman-app:latest"
