name: Build and push with Podman


on:
  push:
    branches: ["main"]


jobs:
  setup:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version


 build:
   needs: setup
   run-on: ununtu-latest
   steps:
     - name: Login to Docker Hub
       run: |
         echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
         podman login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io
     - name: Verify Podman
        run: |
         podman --version
         buildah --version


      - name: Configure Docker Hub auth
        run: |
          mkdir -p ~/.docker
          auth_token=$( echo -n"${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
             | base64 -w0)
          echo "{\"auths\":{\"docker.io\":{\"auth\":\"${auth_token}\"}}}" \
             > ~/.docker/config.json
          chmod 600 ~/..docker/config.json


       - name: Build and push image
         env:
           DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME}}
         run: |
           podman build \
            -t "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/my-podman-app:latest" .
           podman push \
            "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/my-podman-app:latest"
